# Python Machine Learning - Code Examples

# Data Pre-Processing
# 

### Overview

- [Dealing with missing data](#Dealing-with-missing-data)
  - [Eliminating samples or features with missing values](#Eliminating-samples-or-features-with-missing-values)
- [Handling categorical data](#Handling-categorical-data)
  - [Mapping ordinal features](#Mapping-ordinal-features)
  - [Encoding class labels](#Encoding-class-labels)
  - [Performing one-hot encoding on nominal features](#Performing-one-hot-encoding-on-nominal-features)
- [Imputing missing values](#Imputing-missing-values) 


In [1]:
#from IPython.display import Image
%matplotlib inline

In [2]:
# Added version check for recent scikit-learn 0.18 checks
from distutils.version import LooseVersion as Version
from sklearn import __version__ as sklearn_version
#Disable warning
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", category=DeprecationWarning)

###  Dealing with missing data

In [3]:
import pandas as pd
from io import StringIO

csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''



df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [4]:
# print the number of missing 
df.isnull().sum()

A    0
B    0
C    1
D    1
dtype: int64

#### Eliminating samples or features with missing values


In [5]:
#### deleting rows of the data frame
df.dropna()

A    B    C    D
0  1.0  2.0  3.0  4.0

In [6]:
# only drop rows where all columns are NaN
df.dropna(how='all')  

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [7]:
# drop rows that have not at least 4 non-NaN values
df.dropna(thresh=4)

A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
# only drop rows where NaN appear in specific columns (here: 'C')
df.dropna(subset=['C'])

A     B     C    D
0   1.0   2.0   3.0  4.0
2  10.0  11.0  12.0  NaN

In [9]:
# Eliminate the feature with NaN
df.dropna(axis=1)

A     B
0   1.0   2.0
1   5.0   6.0
2  10.0  11.0

## Handling categorical data

In [10]:
import pandas as pd

df = pd.DataFrame([['green', 'M', 10.1, 'class1'],
                   ['red', 'L', 13.5, 'class2'],
                   ['blue', 'XL', 15.3, 'class1']])

df.columns = ['color', 'size', 'price', 'classlabel']
df

color size  price classlabel
0  green    M   10.1     class1
1    red    L   13.5     class2
2   blue   XL   15.3     class1

### Mapping ordinal features

In [11]:
size_mapping = {'XL': 3,
                'L': 2,
                'M': 1}

df['size'] = df['size'].map(size_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [12]:
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['size'].map(inv_size_mapping)

0     M
1     L
2    XL
Name: size, dtype: object

## Encoding class labels

In [13]:
import numpy as np

class_mapping = {label: idx for idx, label in enumerate(np.unique(df['classlabel']))}
class_mapping

{'class1': 0, 'class2': 1}

In [14]:
df['classlabel'] = df['classlabel'].map(class_mapping)
df

color  size  price  classlabel
0  green     1   10.1           0
1    red     2   13.5           1
2   blue     3   15.3           0

In [15]:
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['classlabel'] = df['classlabel'].map(inv_class_mapping)
df

color  size  price classlabel
0  green     1   10.1     class1
1    red     2   13.5     class2
2   blue     3   15.3     class1

In [16]:
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
y = class_le.fit_transform(df['classlabel'].values)
print(np.shape(y),y)
y

(3,) [0 1 0]


array([0, 1, 0])

In [17]:
class_le.inverse_transform(y)


array(['class1', 'class2', 'class1'], dtype=object)

## Performing one-hot encoding on nominal features

In [18]:
X = df[['color', 'size', 'price']].values
#print(X)
color_le = LabelEncoder()
X[:, 0] = color_le.fit_transform(X[:, 0])
print(X.shape)
print(X)

(3, 3)
[[1 1 10.1]
 [2 2 13.5]
 [0 3 15.3]]


In [19]:
from sklearn.preprocessing import OneHotEncoder

print(X)
ohe = OneHotEncoder()
X=ohe.fit_transform(X).toarray()
print(X)

[[1 1 10.1]
 [2 2 13.5]
 [0 3 15.3]]
[[0. 1. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 1.]]


In [20]:
### Using Pandas
X1=pd.get_dummies(df[['price', 'color', 'size']]).values
print(X1)

[[10.1  1.   0.   1.   0. ]
 [13.5  2.   0.   0.   1. ]
 [15.3  3.   1.   0.   0. ]]


#### Remark:  addressing heterogenous data. For instance, applying OneHotEnconder to part of the columns
#### https://jorisvandenbossche.github.io/blog/2018/05/28/scikit-learn-columntransformer/
###### (from sklearn.compose import ColumnTransformer, make_column_transformer)

## Imputing missing values

In [21]:
import pandas as pd
from io import StringIO

csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,,8.0
10.0,11.0,12.0,'''



df = pd.read_csv(StringIO(csv_data))
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   NaN  8.0
2  10.0  11.0  12.0  NaN

In [23]:
from sklearn.impute import SimpleImputer
# type of imputation
imr = SimpleImputer(missing_values=np.nan, strategy='mean')# Calculation
imr = imr.fit(df)
#Application
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1. ,  2. ,  3. ,  4. ],
       [ 5. ,  6. ,  7.5,  8. ],
       [10. , 11. , 12. ,  6. ]])

In [24]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., nan,  8.],
       [10., 11., 12., nan]])

### Bringing features onto the same scale

In [25]:
ex = pd.DataFrame([0, 1, 2, 3, 4, 5])

# standardize
ex[1] = (ex[0] - ex[0].mean()) / ex[0].std(ddof=0)

# Please note that pandas uses ddof=1 (sample standard deviation) 
# by default, whereas NumPy's std method and the StandardScaler
# uses ddof=0 (population standard deviation)

# normalize
ex[2] = (ex[0] - ex[0].min()) / (ex[0].max() - ex[0].min())
ex.columns = ['input', 'standardized', 'normalized']
ex

input  standardized  normalized
0      0      -1.46385         0.0
1      1      -0.87831         0.2
2      2      -0.29277         0.4
3      3       0.29277         0.6
4      4       0.87831         0.8
5      5       1.46385         1.0

##### Remark:  In the pre-processing module  

https://scikit-learn.org/stable/modules/preprocessing.html

commands are available to perform the normalization.


<br>
<br>

## Question:

Download of Machine Learning Repository: Wisconsin breast cancer diagnostic data set.

https://archive.ics.uci.edu/ml/datasets/Breast+Cancer+Wisconsin+(Diagnostic)

and perform the necessary operations to
1. eliminate rows with missing values
2. substitute the missing values.
