# Eigendecompositions
###  eigenvalue  eigendecomposition and singular value decomposition

- [Data matrix](#Data-Matrix)
 - [Centering the Data](#Centering-the-data)
- [The covariance matrix](#the-covariance-matrix)
     - [Eigenvalues](#Eigenvalues)
     - [Eigenvectors and right eigenvectors](#Eigenvectors-and-right-eigenvectors)
- [The kernel matrix](#the-kernel-matrix)
  - [Eigenvalues and Singular Values](#Eigenvalues-and-Singular-Values)
  - [Eigenvectors and left eigenvectors](#Eigenvectors-and-left-eigenvectors)
- [Singular Value Decomposition](#Singular-value-decomposition)
  - [Singular Values](#Singular-values)
  - [Eigenvectors](#Dual)
     

#### Toy Example :
###### Four examples with dimension two


$$
       \begin{array}{c|cc}
       & X_1 & X_2 \\\\ \hline
\mathbf{x}_1  & 1 & 2 \\\\
\mathbf{x}_2  & 3 & 4 \\\\
\mathbf{x}_3 & 3 & 1  \\\\
\mathbf{x}_4 & 1 & 1  \\\\
\end{array}
$$   
With the $4 \times 2$ data matrix $\mathbf{X}$ 
    

Calculate
1.  the mean vector $\boldsymbol{\mu}$   
2.  the covariance matrix $\boldsymbol{\Sigma}$ 
3.  $\mathbf{Z}= \mathbf{X} - \mathbf{1}_4  \boldsymbol{\mu}^T$. Explain the geometric meaning of the operation.
4.  What is the result of $\mathbf{Z}^T \mathbf{Z}$

Note: $\mathbf{1}_4$ is a vector of ones with dimension 4

In [1]:
import numpy as np

%matplotlib inline 
import matplotlib.pyplot as plt 
import matplotlib.gridspec as gridspec 

In [2]:
## The data set
X=np.array([[1,2],[3,4],[3, 1],[1,1]])
X

array([[1, 2],
       [3, 4],
       [3, 1],
       [1, 1]])

In [3]:
# Answer to question 1
mu=np.mean(X,0)
print(' The mean vector', mu)

 The mean vector [2. 2.]


In [4]:
# Answer to question 3
L=np.size(X,0)

H=np.ones((L,1))*mu
print(H)
Z=X-H
print(Z)

[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]
[[-1.  0.]
 [ 1.  2.]
 [ 1. -1.]
 [-1. -1.]]


In [5]:
# Answer to question 4)  (scatter matrix)
Z1=Z.transpose()
S=np.dot(Z1,Z)
S


array([[4., 2.],
       [2., 6.]])

In [6]:
# Covariance matrix ( Sigma on the slides)
C= (1/4)*S

### Questions
1. what is the difference between scatter matrix  $\mathbf{S}$and covariance matrix  $\mathbf{C}$?  Write down the definitions of both.
2. Another similar matrix  is the correlation matrix.  Its non-normalized form is defined as $ \mathbf{R} =\mathbf{X}^T \mathbf{X}$. 
    * What is the dimension of $\mathbf{R}$
    * Write down the expression to compute each entry of $\mathbf{R}$


In [7]:
#Eigendecomposition
from numpy.linalg import eig
values,vectors=eig(S)
print('eigenvectors \n', vectors, '\n eigenvalues \n',values)

a=vectors[:,0]
b=vectors[:,1]
print('\n dot product between aigenvectors:' , np.dot(a,a),np.dot(a,b), np.dot(b,b) )

eigenvectors 
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]] 
 eigenvalues 
 [2.76393202 7.23606798]

 dot product between aigenvectors: 0.9999999999999998 0.0 0.9999999999999998


# The eigenvectors form an orthogonal basis in the feature space

### Questions
1.  Represent geometrically the data $\mathbf{Z}$ and the eigenvectors
1.  Write the code to show that  $ \mathbf{S}=\mathbf{U}\mathbf{\Lambda} \mathbf{U}^T$. Where  $\mathbf{U}$ is the matrix of eigenvectors and $\mathbf{\Lambda}$ is a diagonal matrix with the eigenvalues.
2.  Project the centered data matrix into the direction of the largest eigenvalue. First do the calculations and then write the code.
_ _Remark: the value of the projection for $n-th$ example $\mathbf{z}_n$ is calculated  as $a_n=\mathbf{u}^T\mathbf{z}_n$, where $\mathbf{u}$ is the selected eigenvector _ _
3.  Reconstruct the data 
$\hat{\mathbf{z}}_n=a_n \mathbf{u} $.  
4.  Compute the squared error,   between the reconstructed $\hat{\mathbf{z}}$ and the original, in your data set. Can you antecipate the value of this error.


In [ ]:
values,vectors=eig((1/4)*S)
print('eigenvectors', vectors, '\n eigenvalues',values)

### Question
1. What is the difference between the eigendecompostion of $\mathbf{S}$ and $\frac{\mathbf{S}}{N}$

In [ ]:
# Kernel matrix or dot product matrix
K=np.dot(Z,Z1)
K


### Questions 
1.  What is the dimension of the matrix $\mathbf{K}$? Write down an expression to describe its calculation.
2.  Write an expression that describes the calculation of one the entries of the matrix $\mathbf{K}_{i,j}$. What is the meaning of the expression.
3. Show that $\mathbf{K}= \mathbf{V}\mathbf{\Lambda} \mathbf{V}^T$. Where  $\mathbf{V}$ is the matrix of eigenvectors and $\mathbf{\Lambda}$ is a diagonal matrix with the eigenvalues.

In [ ]:
# The non-zeros eigenvalues of the matrix have the same values as the eigenvalues of the scatter matrix
values,vectors=eig(K)
print('eigenvectors', vectors, '\n eigenvalues',values)

In [ ]:
print(np.dot(vectors[:,0],vectors[:,0]))
print(np.dot(vectors[:,0],vectors[:,1]))

In [6]:
from numpy.linalg import svd

v,d,u=svd(Z)
print('left eigenvectors', v)
print('singular values' ,d)
print(' right eigenvectors', u)



left eigenvectors [[ 0.19543951  0.51166727  0.7472136  -0.3763932 ]
 [-0.82789504  0.12078826  0.3472136   0.4236068 ]
 [ 0.12078826 -0.82789504  0.5472136   0.0236068 ]
 [ 0.51166727  0.19543951  0.1472136   0.8236068 ]]
singular values [2.68999405 1.66250775]
 right eigenvectors [[-0.52573111 -0.85065081]
 [-0.85065081  0.52573111]]


In [7]:
### Eigenvalues and Singular values.

print(list(np.array(d)**2))

[7.236067977499788, 2.7639320225002106]


## Remarks
Given the centered data $\mathbf{Z}$
1.  The left eigenvectors of svd are the eigenvectors of the kernel matrix
2.  The right eigenvectors of the svd  are the eigenvectors of the scatter matrix 
3.  The (non-zero) eigenvalues of kernel and scatter matrix are the square of the singular values.

# FINAL remark

## Singular value decomposition
An $ N \times D$ matrix, where N is the number of examples and $D$ is the dimension of the feature vector, is 
$$
\mathbf{Z}= \mathbf{V} \mathbf{D} \mathbf{U}^T
$$

* The matrices of eigenvectors have orthogonal columns
* the maximum number of non-zero singular values is $ \min(N,D)$

## Eigendecomposition of  the $D \times D $ scatter matrix
$$
\mathbf{S}=\mathbf{U}\mathbf{\Lambda} \mathbf{U}^T
$$

## Eigendecomposition of  the $N \times N$ kernel matrix
$$
\mathbf{K}=\mathbf{V}\mathbf{\Lambda^{(+)}} \mathbf{V}^T 
$$

* the diagonal matrix  $\mathbf{\Lambda^{(+)}}$ has only $D$ elements non zero and are equal to ones the ones in the diagonal of $\mathbf{\Lambda}$

**Finally diagonal entries of $\mathbf{\Lambda} $ are the square of the diagonal entries of $\mathbf{D}$